name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate
        run: |
          python ./scripts/validate.py
      - name: Dump
        run: |
          python ./scripts/pkl.py --update
          python ./scripts/pkl.py --dump json
          python ./scripts/pkl.py --dump jsonnet
          python ./scripts/pkl.py --dump pcf
          python ./scripts/pkl.py --dump plist
          python ./scripts/pkl.py --dump xml
          python ./scripts/pkl.py --dump yaml
      - name: Clear
        run: |
          find . -maxdepth 1 -regextype egrep -not -regex '.|..|\./(.git|dataset-dump.+)' -exec rm -rf {} +
      - name: Readme
        run: echo "Auto builds the latest version of dataset in available formats. Also added bulk build for convenient indexing OpenSearch or Elasticsearch." > README.md
      - name: Save
        run: |
          ls
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git checkout -b dump
          git add .
          git commit -m 'Update dump.'
          git push origin dump --force
