name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python ./scripts/pkl.py --update
      - run: python ./scripts/pkl.py --dump json
