name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dump
        run: |
          python ./scripts/pkl.py --update
          python ./scripts/pkl.py --dump json
      - name: Clear
        run: ls -a | grep -xvF dataset-dump.* | grep -xvF .git | xargs rm -rf -- 2> /dev/null
      - name: Save
        run: |
          ls
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git checkout -b dump
          git add .
          git commit -m 'Update dump.'
          git push origin dump --force
