name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dump
        run: |
          python ./scripts/pkl.py --update
          python ./scripts/pkl.py --dump json
      - uses: actions/checkout@v4
      - name: Save
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git checkout dump || git checkout -b dump
          git commit -m 'Update dump.'
          git push origin dump --force
